export const FETCH_COUNTRY_LIST_AJAXEND = 'FETCH_COUNTRY_LIST_AJAXEND';

export const FETCH_CITY_LIST_AJAXEND = 'FETCH_CITY_LIST_AJAXEND';

export const SELECT_BASE_COUNTRY = 'SELECT_BASE_COUNTRY';
export const SELECT_BASE_CITY = 'SELECT_BASE_CITY';

export const BULK_ADD_CALCULATED_RATES_AJAXEND = 'BULK_ADD_CALCULATED_RATES_AJAXEND';
export const ADD_CALCULATED_RATES_AJAXEND = 'ADD_CALCULATED_RATES_AJAXEND';
export const CLEANUP_CALCULATED_RATES = 'CLEANUP_CALCULATED_RATES';

export const BEGIN_AJAX_CALL = 'BEGIN_AJAX_CALL';

export const SELECT_COMPARETO_COUNTRY = 'SELECT_COMPARETO_COUNTRY';
export const DESELECT_COMPARETO_COUNTRY = 'DESELECT_COMPARETO_COUNTRY';

export const CHANGE_SORT_ORDER = 'CHANGE_SORT_ORDER';
export const SIGNUP_SUCCESS_AJAXEND = 'SIGNUP_SUCCESS_AJAXEND';
export const LOGIN_SUCCESS_AJAXEND = 'LOGIN_SUCCESS_AJAXEND';
export const LOGIN_FAILRE_AJAXEND = 'LOGIN_FAILRE_AJAXEND';
export const CLEAR_LOGIN_ERRORS = 'CLEAR_LOGIN_ERRORS';
export const LOGOUT_USER = 'LOGOUT_USER';

export const FETCH_COUNTRY_CODE_AJAXEND = 'FETCH_COUNTRY_CODE_AJAXEND';
export const FETCH_COUNTRY_CODE = 'FETCH_COUNTRY_CODE';
