export const FETCH_COUNTRY_LIST_SUCCESS = 'FETCH_COUNTRY_LIST_SUCCESS';

export const FETCH_CITY_LIST_SUCCESS = 'FETCH_CITY_LIST_SUCCESS';

export const SELECT_BASE_COUNTRY = 'SELECT_BASE_COUNTRY';
export const SELECT_BASE_CITY = 'SELECT_BASE_CITY';

export const BULK_ADD_CALCULATED_RATES_SUCCESS = 'BULK_ADD_CALCULATED_RATES_SUCCESS';
export const ADD_CALCULATED_RATES_SUCCESS = 'ADD_CALCULATED_RATES_SUCCESS';

export const BEGIN_AJAX_CALL = 'BEGIN_AJAX_CALL';

export const SELECT_COMPARETO_COUNTRY = 'SELECT_COMPARETO_COUNTRY';
export const DESELECT_COMPARETO_COUNTRY = 'DESELECT_COMPARETO_COUNTRY';
